# Nama service
spring.application.name=employee_service

# Port
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_employee
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email SMTP
smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=deafriliart@gmail.com
smtp.password=orxa pbvq dizc dpzt

# Session timeout
server.servlet.session.timeout=60

# Scheduler aktif
spring.task.scheduling.enabled=true